spring:
  application:
    name: suscripciones-api
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5437/gestor_suscripciones}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:04012005}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:4200,https://frontendsistemaclientes-production.up.railway.app}

logging:
  level:
    com.gestor.suscripciones: INFO
